// frontend/components/LoginForm.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'

const props = defineProps<{
    class?: HTMLAttributes['class']
}>()
</script>

<template>
    <form :class="cn('flex flex-col gap-6', props.class)">
        <div class="flex flex-col items-center gap-2 text-center">
            <h1 class="text-2xl font-bold">
                Login to your account
            </h1>
            <p class="text-muted-foreground text-sm text-balance">
                Enter your email below to login to your account
            </p>
        </div>
        <div class="grid gap-6">
            <div class="grid gap-3">
                <Label for="email">Email</Label>
                <Input id="email" type="email" placeholder="m@example.com" required />
            </div>
            <div class="grid gap-3">
                <div class="flex items-center">
                    <Label for="password">Password</Label>
                    <a href="#" class="ml-auto text-sm underline-offset-4 hover:underline">
                        Forgot your password?
                    </a>
                </div>
                <Input id="password" type="password" required />
            </div>
            <Button type="submit" class-name="w-full">
                Login
            </Button>
            <div
                class="after:border-border relative text-center text-sm after:absolute after:inset-0 after:top-1/2 after:z-0 after:flex after:items-center after:border-t">
                <span class="bg-background text-muted-foreground relative z-10 px-2">
                    Or continue with
                </span>
            </div>
            <Button variant="outline" class-name="w-full">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <path
                        d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"
                        fill="currentColor" />
                </svg>
                Login with GitHub
            </Button>
        </div>
        <div class="text-center text-sm">
            Don't have an account?
            <a href="#" class="underline underline-offset-4">
                Sign up
            </a>
        </div>
    </form>
</template>

// frontend-sv/src/lib/components/LoginForm.svelte
<!-- LoginForm.svelte -->
<script lang="ts">
    import {
        superForm,
        type SuperValidated,
        type Infer,
    } from "sveltekit-superforms";
    import { type LoginSchema, loginSchema } from "@/schemas/login-schema";
    import * as Form from "@/components/ui/form";
    import { Input } from "@/components/ui/input";
    import { cn } from "@/utils";
    import { zodClient } from "sveltekit-superforms/adapters";
    import LoaderCircle from "@lucide/svelte/icons/loader-circle";

    let { data }: { data: { form: SuperValidated<Infer<LoginSchema>> } } =
        $props();

    const form = superForm(data.form, {
        validators: zodClient(loginSchema),
    });

    const { form: formData, errors, enhance, delayed, message } = form;
</script>

<div class="grid gap-6">
    <form method="POST" use:enhance>
        {#if $message}
            <div
                class="mb-4 p-3 rounded-md border border-destructive bg-destructive/10 text-destructive text-sm"
            >
                {$message}
            </div>
        {/if}
        <div class="grid gap-4">
            <Form.Field {form} name="email">
                <Form.Control>
                    {#snippet children({ props })}
                        <Form.Label>Email</Form.Label>
                        <Input
                            {...props}
                            type="email"
                            placeholder="m@example.com"
                            autocomplete="email"
                            class={cn(
                                "w-full",
                                $errors.email && "border-destructive",
                            )}
                            bind:value={$formData.email}
                        />
                    {/snippet}
                </Form.Control>
                <Form.Description>
                    Enter the email address associated with your account
                </Form.Description>
                {#if $errors.email}
                    <Form.FieldErrors class="text-destructive text-sm">
                        {$errors.email}
                    </Form.FieldErrors>
                {/if}
            </Form.Field>

            <Form.Field {form} name="password">
                <Form.Control>
                    {#snippet children({ props })}
                        <Form.Label>Password</Form.Label>
                        <Input
                            {...props}
                            type="password"
                            placeholder="••••••••"
                            autocomplete="current-password"
                            class={cn(
                                "w-full",
                                $errors.password && "border-destructive",
                            )}
                            bind:value={$formData.password}
                        />
                    {/snippet}
                </Form.Control>
                {#if $errors.password}
                    <Form.FieldErrors class="text-destructive text-sm">
                        {$errors.password}
                    </Form.FieldErrors>
                {/if}
            </Form.Field>

            <div class="flex items-center justify-between text-sm">
                <!-- <label class="flex items-center gap-2">
                    {@const checked = $formData.rememberMe}
                    <Input type="checkbox" bind:checked={checked} class="w-4 h-4" />
                    <span>Remember me</span>
                </label> -->
                <a href="/forgot-password" class="text-primary hover:underline">
                    Forgot password?
                </a>
            </div>

            <Form.Button class="w-full" disabled={$delayed}>
                {#if $delayed}
                    <div class="flex items-center justify-center gap-2">
                        <LoaderCircle
                            class="h-5 w-5 animate-spin"
                            strokeWidth={2}
                        />
                        <span>Signing in...</span>
                    </div>
                {:else}
                    <span> Sign in</span>
                {/if}
            </Form.Button>
        </div>
    </form>
</div>
