// frontend-sv/src/routes/startups/+page.svelte
<script lang="ts">
    import { Badge } from "@/components/ui/badge";
    import * as Card from "@/components/ui/card";
    import { Input } from "@/components/ui/input";
    import {
        Select,
        SelectContent,
        SelectItem,
        SelectTrigger,
    } from "@/components/ui/select";
    import { Separator } from "@/components/ui/separator";
    import { Skeleton } from "@/components/ui/skeleton";
    import type { PageData } from "./$types";

    let { data }: { data: PageData } = $props();

    // Filter state
    let searchQuery = $state("");
    let selectedIndustry = $state("all");
    let selectedFundingStage = $state("all");
    let isLoading = $state(true);

    // Initialize startups from server data
    let startups = $state(data.startups);
    const industries = data.industries;
    const fundingStages = data.fundingStages;

    // Filtered startups derived value
    let filteredStartups = $derived(
        startups.filter((startup) => {
            const matchesSearch =
                startup.name
                    .toLowerCase()
                    .includes(searchQuery.toLowerCase()) ||
                startup.description
                    .toLowerCase()
                    .includes(searchQuery.toLowerCase());

            const matchesIndustry =
                selectedIndustry === "all" ||
                startup.industry === selectedIndustry;

            const matchesFunding =
                selectedFundingStage === "all" ||
                startup.funding_stage === selectedFundingStage;

            return matchesSearch && matchesIndustry && matchesFunding;
        }),
    );

    // Initialize component and set loading to false
    $effect(() => {
        isLoading = false;
    });

    // Reset filters
    function resetFilters() {
        searchQuery = "";
        selectedIndustry = "all";
        selectedFundingStage = "all";
    }

    // Format currency
    function formatCurrency(amount: number): string {
        return new Intl.NumberFormat("en-US", {
            style: "currency",
            currency: "USD",
            maximumFractionDigits: 0,
        }).format(amount);
    }

    // Event handler for button clicks
    function handleReset() {
        resetFilters();
    }
</script>

<div class="container mx-auto py-8 px-4 md:px-6">
    <div class="flex flex-col gap-4">
        <div class="flex flex-col gap-2">
            <h1 class="text-3xl font-bold tracking-tight">Startups</h1>
            <p class="text-muted-foreground">
                Discover and connect with innovative startups
            </p>
        </div>

        <Separator class="my-4" />

        <!-- Filters Section -->
        <div class="grid gap-4 md:grid-cols-[1fr_auto_auto] items-end">
            <!-- Search Bar -->
            <div class="relative">
                <Input
                    type="search"
                    placeholder="Search by name or description..."
                    bind:value={searchQuery}
                />
            </div>

            <!-- Using a standard select instead of shadcn select until we confirm import structure -->
            <div class="w-full md:w-[180px]">
                <!-- bind:value={selectedIndustry} -->
                <Select
                    type="single"
                    bind:value={selectedIndustry}
                    name="industry"
                >
                    <SelectTrigger class="w-full p-2 border rounded-md">
                        {selectedIndustry === "all"
                            ? "All Industry"
                            : selectedIndustry}
                    </SelectTrigger>
                    <SelectContent>
                        {#each industries as industry}
                            <SelectItem
                                value={industry}
                                label={industry.toUpperCase()}
                            />
                        {/each}
                    </SelectContent>
                </Select>
            </div>

            <div class="w-full md:w-[180px]">
                <Select
                    type="single"
                    bind:value={selectedFundingStage}
                    name="funding"
                >
                    <SelectTrigger class="w-full p-2 border rounded-md">
                        {selectedFundingStage === "all"
                            ? "All Stages"
                            : selectedFundingStage}
                    </SelectTrigger>
                    <SelectContent>
                        {#each fundingStages as stage}
                            <SelectItem
                                value={stage}
                                label={stage.toUpperCase()}
                            />
                        {/each}
                    </SelectContent>
                </Select>
            </div>

            <!-- Reset Filter Button -->
            <button
                class="inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 h-9 px-4 py-2 border border-input bg-background hover:bg-accent hover:text-accent-foreground shadow-sm w-full md:w-auto"
                onclick={handleReset}
            >
                Reset Filters
            </button>
        </div>

        <!-- Results Count -->
        <div class="text-sm text-muted-foreground mt-2">
            {#if !isLoading}
                {filteredStartups.length}
                {filteredStartups.length === 1 ? "startup" : "startups"} found
            {/if}
        </div>

        <!-- Startups Grid -->
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mt-6">
            {#if isLoading}
                {#each Array(6) as _}
                    <div class="flex flex-col gap-4">
                        <Skeleton class="h-[200px] w-full rounded-lg" />
                        <div class="space-y-2">
                            <Skeleton class="h-4 w-[250px]" />
                            <Skeleton class="h-4 w-[200px]" />
                        </div>
                    </div>
                {/each}
            {:else if filteredStartups.length === 0}
                <div class="col-span-full flex justify-center py-12">
                    <div class="text-center">
                        <h3 class="text-lg font-medium">No startups found</h3>
                        <p class="text-muted-foreground mt-1">
                            Try adjusting your filters or search term
                        </p>
                        <button
                            class="inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 h-9 px-4 py-2 border border-input bg-background hover:bg-accent hover:text-accent-foreground shadow-sm mt-4"
                            onclick={handleReset}
                        >
                            Reset Filters
                        </button>
                    </div>
                </div>
            {:else}
                {#each filteredStartups as startup (startup.id)}
                    <Card.Root class="overflow-hidden h-full flex flex-col">
                        <div class="aspect-video bg-muted relative">
                            <img
                                src={startup.logo_url}
                                alt={`${startup.name} logo`}
                                class="object-cover w-full h-full"
                            />
                            <Badge class="absolute top-2 right-2"
                                >{startup.funding_stage}</Badge
                            >
                        </div>
                        <Card.Header>
                            <div class="flex justify-between items-start">
                                <Card.Title>{startup.name}</Card.Title>
                                <Badge variant="outline"
                                    >{startup.industry}</Badge
                                >
                            </div>
                            <Card.Description
                                >{startup.location} • Founded {startup.founded_year}</Card.Description
                            >
                        </Card.Header>
                        <Card.Content class="flex-grow">
                            <p>{startup.description}</p>
                            <div class="grid grid-cols-2 gap-2 mt-4 text-sm">
                                <div>
                                    <span class="text-muted-foreground"
                                        >Team:</span
                                    >
                                    {startup.team_size} people
                                </div>
                                <div>
                                    <span class="text-muted-foreground"
                                        >Goal:</span
                                    >
                                    {formatCurrency(startup.funding_goal)}
                                </div>
                                <div class="col-span-2">
                                    <span class="text-muted-foreground"
                                        >Market:</span
                                    >
                                    {startup.target_market}
                                </div>
                                <div class="col-span-2">
                                    <span class="text-muted-foreground"
                                        >Business model:</span
                                    >
                                    {startup.business_model}
                                </div>
                            </div>
                        </Card.Content>
                        <Card.Footer class="flex justify-between">
                            <a
                                href={startup.website}
                                target="_blank"
                                rel="noopener noreferrer"
                                class="inline-flex items-center justify-center whitespace-nowrap font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 h-8 rounded-md px-3 text-xs border border-input bg-background hover:bg-accent hover:text-accent-foreground shadow-sm"
                            >
                                Visit Website
                            </a>
                            <a
                                href={startup.pitch_deck_url}
                                target="_blank"
                                rel="noopener noreferrer"
                                class="inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 h-8 rounded-md px-3 text-xs bg-primary text-primary-foreground hover:bg-primary/90 shadow"
                            >
                                View Pitch
                            </a>
                        </Card.Footer>
                    </Card.Root>
                {/each}
            {/if}
        </div>
    </div>
</div>

// frontend/pages/dashboard/investor/startups/index.vue
<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Badge } from '@/components/ui/badge'
import { useInvestor } from '@/composables/useInvestor'
import { Slider } from '@/components/ui/slider'
import { Checkbox } from '@/components/ui/checkbox'

interface Startup {
  id: string
  name: string
  shortDescription: string
  stage: string
  industry: string
  region: string
  fundingNeeded: string
  fundingRaised: number
  teamSize: number
  foundedYear: number
  metrics: {
    revenue?: number
    growth?: number
    burnRate?: number
  }
  tags: string[]
}

const { investor, isLoading, error } = useInvestor()

// State for startups
const startups = ref<Startup[]>([])
const filteredStartups = ref<Startup[]>([])

// Filter states
const searchQuery = ref('')
const selectedIndustry = ref('')
const selectedStage = ref('')
const selectedRegion = ref('')
const sortBy = ref('newest')
const viewMode = ref<'grid' | 'list'>('grid')
const fundingRange = ref([0, 10000000])
const teamSizeRange = ref([1, 100])
const selectedTags = ref<string[]>([])

// Available options
const industries = [
  'Technology',
  'Healthcare',
  'FinTech',
  'E-commerce',
  'AI/ML',
  'CleanTech',
  'EdTech',
  'SaaS',
  'Biotech',
  'Consumer'
]

const stages = [
  'Pre-seed',
  'Seed',
  'Series A',
  'Series B',
  'Series C+'
]

const regions = [
  'North America',
  'Europe',
  'Asia',
  'South America',
  'Africa',
  'Oceania'
]

const tags = [
  'B2B',
  'B2C',
  'Marketplace',
  'Mobile',
  'Web',
  'Enterprise',
  'Deep Tech',
  'Social Impact',
  'Hardware',
  'Blockchain'
]

// Computed properties for filtering
const filteredResults = computed(() => {
  let results = [...startups.value]

  // Apply search query
  if (searchQuery.value) {
    const query = searchQuery.value.toLowerCase()
    results = results.filter(startup => 
      startup.name.toLowerCase().includes(query) ||
      startup.shortDescription.toLowerCase().includes(query) ||
      startup.tags.some(tag => tag.toLowerCase().includes(query))
    )
  }

  // Apply industry filter
  if (selectedIndustry.value) {
    results = results.filter(startup => startup.industry === selectedIndustry.value)
  }

  // Apply stage filter
  if (selectedStage.value) {
    results = results.filter(startup => startup.stage === selectedStage.value)
  }

  // Apply region filter
  if (selectedRegion.value) {
    results = results.filter(startup => startup.region === selectedRegion.value)
  }

  // Apply funding range filter
  results = results.filter(startup => {
    const funding = parseFloat(startup.fundingNeeded.replace(/[^0-9.]/g, ''))
    return funding >= fundingRange.value[0] && funding <= fundingRange.value[1]
  })

  // Apply team size filter
  results = results.filter(startup => 
    startup.teamSize >= teamSizeRange.value[0] && 
    startup.teamSize <= teamSizeRange.value[1]
  )

  // Apply tags filter
  if (selectedTags.value.length > 0) {
    results = results.filter(startup => 
      selectedTags.value.every(tag => startup.tags.includes(tag))
    )
  }

  // Apply sorting
  switch (sortBy.value) {
    case 'newest':
      results.sort((a, b) => b.foundedYear - a.foundedYear)
      break
    case 'funding':
      results.sort((a, b) => b.fundingRaised - a.fundingRaised)
      break
    case 'growth':
      results.sort((a, b) => (b.metrics.growth || 0) - (a.metrics.growth || 0))
      break
  }

  return results
})

onMounted(async () => {
  // TODO: Implement API call to fetch startups
  // For now, using mock data
  startups.value = [
    {
      id: '1',
      name: 'TechStart AI',
      shortDescription: 'AI-powered business analytics platform',
      stage: 'Series A',
      industry: 'Technology',
      region: 'North America',
      fundingNeeded: '$5M',
      fundingRaised: 2000000,
      teamSize: 25,
      foundedYear: 2022,
      metrics: {
        revenue: 500000,
        growth: 150,
        burnRate: 15
      },
      tags: ['B2B', 'AI/ML', 'SaaS']
    },
    // Add more mock startups here
  ]
})

const toggleTag = (tag: string) => {
  const index = selectedTags.value.indexOf(tag)
  if (index === -1) {
    selectedTags.value.push(tag)
  } else {
    selectedTags.value.splice(index, 1)
  }
}

const formatCurrency = (amount: number) => {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0
  }).format(amount)
}
</script>

<template>
  <div class="container mx-auto py-8 space-y-8">
    <!-- Loading State -->
    <div v-if="isLoading" class="flex justify-center items-center h-64">
      <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900"></div>
    </div>

    <!-- Error State -->
    <div v-else-if="error" class="text-center text-red-500">
      {{ error }}
    </div>

    <!-- Main Content -->
    <div v-else>
      <!-- Header Section -->
      <div class="flex justify-between items-center mb-8">
        <div>
          <h1 class="text-3xl font-bold">Startup Directory</h1>
          <p class="text-muted-foreground">Browse and discover promising startups</p>
        </div>
        <div class="flex gap-2">
          <Button variant="outline" @click="viewMode = 'grid'">
            <i class="fas fa-th-large mr-2"></i>Grid
          </Button>
          <Button variant="outline" @click="viewMode = 'list'">
            <i class="fas fa-list mr-2"></i>List
          </Button>
        </div>
      </div>

      <!-- Filter Section -->
      <Card class="mb-8">
        <CardContent class="pt-6">
          <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <!-- Search -->
            <div class="col-span-full">
              <Input
                v-model="searchQuery"
                placeholder="Search startups by name, description, or tags..."
                class="w-full"
              />
            </div>

            <!-- Industry -->
            <div>
              <label class="text-sm font-medium mb-2 block">Industry</label>
              <Select v-model="selectedIndustry">
                <SelectTrigger>
                  <SelectValue placeholder="Select Industry" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="">All Industries</SelectItem>
                  <SelectItem v-for="industry in industries" :key="industry" :value="industry">
                    {{ industry }}
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>

            <!-- Stage -->
            <div>
              <label class="text-sm font-medium mb-2 block">Stage</label>
              <Select v-model="selectedStage">
                <SelectTrigger>
                  <SelectValue placeholder="Select Stage" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="">All Stages</SelectItem>
                  <SelectItem v-for="stage in stages" :key="stage" :value="stage">
                    {{ stage }}
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>

            <!-- Region -->
            <div>
              <label class="text-sm font-medium mb-2 block">Region</label>
              <Select v-model="selectedRegion">
                <SelectTrigger>
                  <SelectValue placeholder="Select Region" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="">All Regions</SelectItem>
                  <SelectItem v-for="region in regions" :key="region" :value="region">
                    {{ region }}
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>

            <!-- Funding Range -->
            <div>
              <label class="text-sm font-medium mb-2 block">
                Funding Needed: {{ formatCurrency(fundingRange[0]) }} - {{ formatCurrency(fundingRange[1]) }}
              </label>
              <Slider
                v-model="fundingRange"
                :min="0"
                :max="10000000"
                :step="100000"
                class="w-full"
              />
            </div>

            <!-- Team Size -->
            <div>
              <label class="text-sm font-medium mb-2 block">
                Team Size: {{ teamSizeRange[0] }} - {{ teamSizeRange[1] }}
              </label>
              <Slider
                v-model="teamSizeRange"
                :min="1"
                :max="100"
                :step="1"
                class="w-full"
              />
            </div>

            <!-- Sort By -->
            <div>
              <label class="text-sm font-medium mb-2 block">Sort By</label>
              <Select v-model="sortBy">
                <SelectTrigger>
                  <SelectValue placeholder="Sort By" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="newest">Newest First</SelectItem>
                  <SelectItem value="funding">Funding Amount</SelectItem>
                  <SelectItem value="growth">Growth Rate</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <!-- Tags -->
            <div class="col-span-full">
              <label class="text-sm font-medium mb-2 block">Tags</label>
              <div class="flex flex-wrap gap-2">
                <Badge
                  v-for="tag in tags"
                  :key="tag"
                  :variant="selectedTags.includes(tag) ? 'default' : 'outline'"
                  class="cursor-pointer"
                  @click="toggleTag(tag)"
                >
                  {{ tag }}
                </Badge>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      <!-- Results Count -->
      <div class="mb-4">
        <p class="text-sm text-muted-foreground">
          Showing {{ filteredResults.length }} startups
        </p>
      </div>

      <!-- Grid View -->
      <div v-if="viewMode === 'grid'" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        <Card v-for="startup in filteredResults" :key="startup.id" class="hover:shadow-lg transition-shadow">
          <CardHeader>
            <div class="flex justify-between items-start">
              <div>
                <CardTitle>{{ startup.name }}</CardTitle>
                <CardDescription>{{ startup.shortDescription }}</CardDescription>
              </div>
              <Badge>{{ startup.stage }}</Badge>
            </div>
          </CardHeader>
          <CardContent>
            <div class="space-y-4">
              <div class="flex gap-2 flex-wrap">
                <Badge variant="secondary">{{ startup.industry }}</Badge>
                <Badge variant="secondary">{{ startup.region }}</Badge>
                <Badge v-for="tag in startup.tags" :key="tag" variant="outline">
                  {{ tag }}
                </Badge>
              </div>
              
              <div class="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <p class="text-muted-foreground">Funding Needed</p>
                  <p class="font-medium">{{ startup.fundingNeeded }}</p>
                </div>
                <div>
                  <p class="text-muted-foreground">Team Size</p>
                  <p class="font-medium">{{ startup.teamSize }} people</p>
                </div>
                <div>
                  <p class="text-muted-foreground">Founded</p>
                  <p class="font-medium">{{ startup.foundedYear }}</p>
                </div>
                <div>
                  <p class="text-muted-foreground">Growth</p>
                  <p class="font-medium">{{ startup.metrics.growth }}%</p>
                </div>
              </div>

              <div class="flex justify-between items-center pt-4">
                <Button variant="outline">View Details</Button>
                <Button>Save</Button>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <!-- List View -->
      <div v-else class="space-y-4">
        <Card v-for="startup in filteredResults" :key="startup.id" class="hover:shadow-lg transition-shadow">
          <CardContent class="p-6">
            <div class="flex items-start justify-between">
              <div class="space-y-4 flex-1">
                <div class="flex items-center gap-4">
                  <h3 class="text-lg font-semibold">{{ startup.name }}</h3>
                  <Badge>{{ startup.stage }}</Badge>
                </div>
                <p class="text-muted-foreground">{{ startup.shortDescription }}</p>
                <div class="flex gap-2 flex-wrap">
                  <Badge variant="secondary">{{ startup.industry }}</Badge>
                  <Badge variant="secondary">{{ startup.region }}</Badge>
                  <Badge v-for="tag in startup.tags" :key="tag" variant="outline">
                    {{ tag }}
                  </Badge>
                </div>
                <div class="grid grid-cols-4 gap-4 text-sm">
                  <div>
                    <p class="text-muted-foreground">Funding Needed</p>
                    <p class="font-medium">{{ startup.fundingNeeded }}</p>
                  </div>
                  <div>
                    <p class="text-muted-foreground">Team Size</p>
                    <p class="font-medium">{{ startup.teamSize }} people</p>
                  </div>
                  <div>
                    <p class="text-muted-foreground">Founded</p>
                    <p class="font-medium">{{ startup.foundedYear }}</p>
                  </div>
                  <div>
                    <p class="text-muted-foreground">Growth</p>
                    <p class="font-medium">{{ startup.metrics.growth }}%</p>
                  </div>
                </div>
              </div>
              <div class="flex gap-2 ml-4">
                <Button variant="outline">View Details</Button>
                <Button>Save</Button>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  </div>
</template>
