// frontend-sv/src/lib/components/file-upload.svelte
<script lang="ts">
    import { Button } from "$lib/components/ui/button";
    import { createEventDispatcher } from "svelte";

    export let accept = "*";
    export let maxSize = 5; // In MB
    export let multiple = false;
    export let files: File[] = [];

    const dispatch = createEventDispatcher<{
        upload: { files: File[] };
        remove: { index: number };
    }>();

    function formatFileSize(bytes: number): string {
        if (bytes === 0) return "0 B";
        const k = 1024;
        const sizes = ["B", "KB", "MB", "GB"];
        const i = Math.floor(Math.log(bytes) / Math.log(k));
        return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + " " + sizes[i];
    }

    function handleFileChange(event: Event) {
        const input = event.target as HTMLInputElement;
        if (!input.files?.length) return;

        const selectedFiles: File[] = [];
        let hasInvalidSize = false;

        for (let i = 0; i < input.files.length; i++) {
            const file = input.files[i];
            // Check file size
            if (file.size > maxSize * 1024 * 1024) {
                hasInvalidSize = true;
                continue;
            }
            selectedFiles.push(file);
        }

        if (hasInvalidSize) {
            alert(`One or more files exceed the maximum size of ${maxSize}MB.`);
        }

        if (selectedFiles.length) {
            files = selectedFiles;
            dispatch("upload", { files: selectedFiles });
        }

        // Reset input so the same file can be selected again if needed
        input.value = "";
    }

    function removeFile(index: number) {
        files = files.filter((_, i) => i !== index);
        dispatch("remove", { index });
    }

    function removeAllFiles() {
        files = [];
        dispatch("remove", { index: -1 });
    }
</script>

<div class="flex flex-col gap-2">
    <div
        class="border-2 border-dashed border-primary/20 rounded-lg p-6 text-center hover:border-primary/50 transition-colors"
    >
        <input
            type="file"
            {accept}
            {multiple}
            class="hidden"
            id="file-upload"
            onchange={handleFileChange}
        />
        <label for="file-upload" class="cursor-pointer">
            <div class="flex flex-col items-center gap-2">
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="h-8 w-8 text-muted-foreground"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                >
                    <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"
                    />
                </svg>
                <span class="text-sm font-medium">
                    {#if files.length}
                        Replace files
                    {:else}
                        Click to upload or drag and drop
                    {/if}
                </span>
                <span class="text-xs text-muted-foreground">
                    {accept.replace(/\*/g, "All")} (Max: {maxSize}MB)
                </span>
            </div>
        </label>
    </div>

    {#if files.length > 0}
        <div class="mt-2 space-y-2">
            {#each files as file, index}
                <div
                    class="flex items-center justify-between p-2 bg-muted rounded-md"
                >
                    <div class="flex items-center gap-2 truncate">
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            class="h-5 w-5 text-muted-foreground"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke="currentColor"
                        >
                            <path
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                stroke-width="2"
                                d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
                            />
                        </svg>
                        <div class="truncate">
                            <p class="text-sm truncate">{file.name}</p>
                            <p class="text-xs text-muted-foreground">
                                {formatFileSize(file.size)}
                            </p>
                        </div>
                    </div>
                    <Button
                        variant="ghost"
                        size="icon"
                        onclick={() => removeFile(index)}
                        class="h-8 w-8"
                    >
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            class="h-4 w-4"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke="currentColor"
                        >
                            <path
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                stroke-width="2"
                                d="M6 18L18 6M6 6l12 12"
                            />
                        </svg>
                        <span class="sr-only">Remove</span>
                    </Button>
                </div>
            {/each}

            {#if files.length > 1}
                <Button
                    variant="outline"
                    size="sm"
                    onclick={removeAllFiles}
                    class="w-full mt-2"
                >
                    Remove All Files
                </Button>
            {/if}
        </div>
    {/if}
</div>

// migrate/frontend/components/FileUpload.vue
<script setup lang="ts">
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Progress } from '@/components/ui/progress'
import { CheckCircle2, File, Upload, X } from 'lucide-vue-next'

interface UploadedFile {
  id: string
  name: string
  size: number
  type: string
  progress: number
  status: 'uploading' | 'success' | 'error'
  url?: string
}

const props = defineProps<{
  accept?: string
  maxSize?: number // in MB
  multiple?: boolean
}>()

const emit = defineEmits<{
  (e: 'upload', files: File[]): void
  (e: 'remove', fileId: string): void
}>()

const files = ref<UploadedFile[]>([])
const isDragging = ref(false)
const fileInput = ref<HTMLInputElement | null>(null)

const handleDragOver = (e: DragEvent) => {
  e.preventDefault()
  isDragging.value = true
}

const handleDragLeave = (e: DragEvent) => {
  e.preventDefault()
  isDragging.value = false
}

const handleDrop = (e: DragEvent) => {
  e.preventDefault()
  isDragging.value = false
  const droppedFiles = e.dataTransfer?.files
  if (droppedFiles) {
    handleFiles(droppedFiles)
  }
}

const handleFileSelect = (e: Event) => {
  const input = e.target as HTMLInputElement
  if (input.files) {
    handleFiles(input.files)
  }
}

const handleFiles = (fileList: FileList) => {
  const newFiles = Array.from(fileList).map(file => ({
    id: crypto.randomUUID(),
    name: file.name,
    size: file.size,
    type: file.type,
    progress: 0,
    status: 'uploading' as const
  }))

  files.value.push(...newFiles)
  emit('upload', Array.from(fileList))

  // Simulate upload progress
  newFiles.forEach(file => {
    let progress = 0
    const interval = setInterval(() => {
      progress += 10
      const fileIndex = files.value.findIndex(f => f.id === file.id)
      if (fileIndex !== -1) {
        files.value[fileIndex].progress = progress
        if (progress >= 100) {
          files.value[fileIndex].status = 'success'
          files.value[fileIndex].url = URL.createObjectURL(fileList[0])
          clearInterval(interval)
        }
      }
    }, 200)
  })
}

const removeFile = (fileId: string) => {
  const fileIndex = files.value.findIndex(f => f.id === fileId)
  if (fileIndex !== -1) {
    const file = files.value[fileIndex]
    if (file.url) {
      URL.revokeObjectURL(file.url)
    }
    files.value.splice(fileIndex, 1)
    emit('remove', fileId)
  }
}

const formatFileSize = (bytes: number) => {
  if (bytes === 0) return '0 Bytes'
  const k = 1024
  const sizes = ['Bytes', 'KB', 'MB', 'GB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i]
}
</script>

<template>
  <Card>
    <CardHeader>
      <CardTitle>Upload Files</CardTitle>
      <CardDescription>Upload pitch decks, documents, or other files</CardDescription>
    </CardHeader>
    <CardContent>
      <div
        class="border-2 border-dashed rounded-lg p-8 text-center"
        :class="{ 'border-primary bg-primary/5': isDragging }"
        @dragover="handleDragOver"
        @dragleave="handleDragLeave"
        @drop="handleDrop"
      >
        <input
          ref="fileInput"
          type="file"
          :accept="accept"
          :multiple="multiple"
          class="hidden"
          @change="handleFileSelect"
        />
        <div class="flex flex-col items-center gap-2">
          <Upload class="h-8 w-8 text-muted-foreground" />
          <p class="text-sm text-muted-foreground">
            Drag and drop files here, or
            <button
              class="text-primary hover:underline"
              @click="fileInput?.click()"
            >
              browse
            </button>
          </p>
          <p class="text-xs text-muted-foreground">
            Supported formats: PDF, DOC, DOCX, PPT, PPTX
            <template v-if="maxSize">
              (Max size: {{ maxSize }}MB)
            </template>
          </p>
        </div>
      </div>

      <!-- Uploaded Files -->
      <div v-if="files.length > 0" class="mt-4 space-y-4">
        <div v-for="file in files" :key="file.id" class="flex items-center gap-4 p-4 border rounded-lg">
          <File class="h-8 w-8 text-muted-foreground" />
          <div class="flex-1 min-w-0">
            <p class="text-sm font-medium truncate">{{ file.name }}</p>
            <p class="text-xs text-muted-foreground">{{ formatFileSize(file.size) }}</p>
            <Progress v-if="file.status === 'uploading'" :value="file.progress" class="mt-2" />
          </div>
          <div class="flex items-center gap-2">
            <CheckCircle2 v-if="file.status === 'success'" class="h-5 w-5 text-green-500" />
            <Button
              v-if="file.status === 'success'"
              variant="ghost"
              size="icon"
              @click="removeFile(file.id)"
            >
              <X class="h-4 w-4" />
            </Button>
          </div>
        </div>
      </div>
    </CardContent>
  </Card>
</template>
