// frontend-sv/src/routes/dashboard/investor/+page.svelte
<script lang="ts">
	import {
		Card,
		CardContent,
		CardDescription,
		CardHeader,
		CardTitle,
	} from "$lib/components/ui/card";
	import { Button } from "$lib/components/ui/button";
	import { Progress } from "$lib/components/ui/progress";
	import { Badge } from "$lib/components/ui/badge";
	import {
	Briefcase,
	TrendingUp,
	Building2,
	DollarSign,
	Target,
	Calendar,
	ArrowRight,
	Plus,
	Eye,
	Star,
} from "@lucide/svelte";

	export let data: { user: any };

	const { user } = data;

	// Mock data - in real app, this would come from API
	const portfolioStats = {
		totalInvested: 2500000,
		portfolioValue: 3200000,
		totalReturn: 28,
		activeInvestments: 8,
		newOpportunities: 15,
		upcomingMeetings: 4,
	};

	const recentDeals = [
		{
			startup: "TechFlow Solutions",
			amount: 500000,
			status: "due_diligence",
			type: "Series A",
			industry: "SaaS",
			rating: 4.5,
		},
		{
			startup: "GreenEnergy Corp",
			amount: 750000,
			status: "negotiating",
			type: "Series B",
			industry: "CleanTech",
			rating: 4.2,
		},
		{
			startup: "HealthTech Innovations",
			amount: 300000,
			status: "evaluating",
			type: "Seed",
			industry: "HealthTech",
			rating: 4.8,
		},
	];

	function getStatusColor(status: string) {
		switch (status) {
			case "due_diligence":
				return "bg-blue-500";
			case "negotiating":
				return "bg-yellow-500";
			case "evaluating":
				return "bg-purple-500";
			case "closed":
				return "bg-green-500";
			default:
				return "bg-gray-500";
		}
	}

	function getStatusText(status: string) {
		switch (status) {
			case "due_diligence":
				return "Due Diligence";
			case "negotiating":
				return "Negotiating";
			case "evaluating":
				return "Evaluating";
			case "closed":
				return "Closed";
			default:
				return "Unknown";
		}
	}

	function formatCurrency(amount: number) {
		return new Intl.NumberFormat("en-US", {
			style: "currency",
			currency: "USD",
			minimumFractionDigits: 0,
			maximumFractionDigits: 0,
		}).format(amount);
	}
</script>

<svelte:head>
	<title>Investor Dashboard - StartupConnect</title>
	<meta
		name="description"
		content="Manage your investment portfolio and discover new opportunities"
	/>
</svelte:head>

<div class="container py-8">
	<div class="max-w-7xl mx-auto">
		<!-- Header -->
		<div class="mb-8">
			<h1 class="text-3xl font-bold mb-2">Investor Dashboard</h1>
			<p class="text-muted-foreground text-lg">
				Manage your portfolio, track deals, and discover new investment
				opportunities
			</p>
		</div>

		<!-- Key Metrics -->
		<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
			<Card>
				<CardHeader
					class="flex flex-row items-center justify-between space-y-0 pb-2"
				>
					<CardTitle class="text-sm font-medium"
						>Total Invested</CardTitle
					>
					<DollarSign class="h-4 w-4 text-muted-foreground" />
				</CardHeader>
				<CardContent>
					<div class="text-2xl font-bold">
						{formatCurrency(portfolioStats.totalInvested)}
					</div>
					<p class="text-xs text-muted-foreground">All time</p>
				</CardContent>
			</Card>

			<Card>
				<CardHeader
					class="flex flex-row items-center justify-between space-y-0 pb-2"
				>
					<CardTitle class="text-sm font-medium"
						>Portfolio Value</CardTitle
					>
					<TrendingUp class="h-4 w-4 text-muted-foreground" />
				</CardHeader>
				<CardContent>
					<div class="text-2xl font-bold">
						{formatCurrency(portfolioStats.portfolioValue)}
					</div>
					<p class="text-xs text-green-600">
						+{portfolioStats.totalReturn}% return
					</p>
				</CardContent>
			</Card>

			<Card>
				<CardHeader
					class="flex flex-row items-center justify-between space-y-0 pb-2"
				>
					<CardTitle class="text-sm font-medium"
						>Active Investments</CardTitle
					>
					<Briefcase class="h-4 w-4 text-muted-foreground" />
				</CardHeader>
				<CardContent>
					<div class="text-2xl font-bold">
						{portfolioStats.activeInvestments}
					</div>
					<p class="text-xs text-muted-foreground">Companies</p>
				</CardContent>
			</Card>

			<Card>
				<CardHeader
					class="flex flex-row items-center justify-between space-y-0 pb-2"
				>
					<CardTitle class="text-sm font-medium"
						>New Opportunities</CardTitle
					>
					<Building2 class="h-4 w-4 text-muted-foreground" />
				</CardHeader>
				<CardContent>
					<div class="text-2xl font-bold">
						{portfolioStats.newOpportunities}
					</div>
					<p class="text-xs text-muted-foreground">This week</p>
				</CardContent>
			</Card>
		</div>

		<!-- Quick Actions -->
		<div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
			<Card
				class="hover:shadow-lg transition-shadow cursor-pointer group"
			>
				<CardHeader>
					<div class="flex items-center space-x-3">
						<div class="p-2 rounded-lg bg-blue-500 text-white">
							<Briefcase class="h-5 w-5" />
						</div>
						<div>
							<CardTitle class="text-lg">Portfolio</CardTitle>
							<CardDescription
								>View and manage your investments</CardDescription
							>
						</div>
					</div>
				</CardHeader>
				<CardContent>
					          <a href="/dashboard/investor/portfolio" class="flex items-center justify-center">
            <Button variant="outline" class="w-full group-hover:bg-primary group-hover:text-primary-foreground transition-colors">
              View Portfolio
              <ArrowRight class="ml-2 h-4 w-4" />
            </Button>
          </a>
				</CardContent>
			</Card>

			<Card
				class="hover:shadow-lg transition-shadow cursor-pointer group"
			>
				<CardHeader>
					<div class="flex items-center space-x-3">
						<div class="p-2 rounded-lg bg-green-500 text-white">
							<TrendingUp class="h-5 w-5" />
						</div>
						<div>
							<CardTitle class="text-lg">Deals</CardTitle>
							<CardDescription
								>Track active and potential deals</CardDescription
							>
						</div>
					</div>
				</CardHeader>
				<CardContent>
					          <a href="/dashboard/investor/deals" class="flex items-center justify-center">
            <Button variant="outline" class="w-full group-hover:bg-primary group-hover:text-primary-foreground transition-colors">
              Manage Deals
              <ArrowRight class="ml-2 h-4 w-4" />
            </Button>
          </a>
				</CardContent>
			</Card>

			<Card
				class="hover:shadow-lg transition-shadow cursor-pointer group"
			>
				<CardHeader>
					<div class="flex items-center space-x-3">
						<div
							class="p-2 rounded-lg bg-purple-500 text-white"
						>
							<Building2 class="h-5 w-5" />
						</div>
						<div>
							<CardTitle class="text-lg">Startups</CardTitle>
							<CardDescription
								>Discover new opportunities</CardDescription
							>
						</div>
					</div>
				</CardHeader>
				<CardContent>
					          <a href="/dashboard/investor/startups" class="flex items-center justify-center">
            <Button variant="outline" class="w-full group-hover:bg-primary group-hover:text-primary-foreground transition-colors">
              Browse Startups
              <ArrowRight class="ml-2 h-4 w-4" />
            </Button>
          </a>
				</CardContent>
			</Card>
		</div>

		<!-- Recent Deals & Upcoming -->
		<div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
			<!-- Recent Deals -->
			<Card>
				<CardHeader>
					<CardTitle class="flex items-center justify-between">
						<span>Recent Deals</span>
						<Button variant="outline" size="sm">
							<Plus class="h-4 w-4 mr-2" />
							New Deal
						</Button>
					</CardTitle>
					<CardDescription
						>Your latest investment activities</CardDescription
					>
				</CardHeader>
				<CardContent>
					<div class="space-y-4">
						{#each recentDeals as deal}
							<div
								class="flex items-center space-x-3 p-3 rounded-lg bg-muted/50"
							>
								<div
									class="w-2 h-2 rounded-full {getStatusColor(
										deal.status,
									)}"
								></div>
								<div class="flex-1">
									<div
										class="flex items-center justify-between mb-1"
									>
										<p class="text-sm font-medium">
											{deal.startup}
										</p>
										<div
											class="flex items-center space-x-1"
										>
											<Star
												class="h-3 w-3 text-yellow-500 fill-current"
											/>
											<span
												class="text-xs text-muted-foreground"
												>{deal.rating}</span
											>
										</div>
									</div>
									<div
										class="flex items-center space-x-2 text-xs text-muted-foreground"
									>
										<span
											>{formatCurrency(deal.amount)}</span
										>
										<span>•</span>
										<span>{deal.type}</span>
										<span>•</span>
										<span>{deal.industry}</span>
									</div>
									<div
										class="flex items-center space-x-2 mt-1"
									>
										<Badge
											variant="secondary"
											class="text-xs"
										>
											{getStatusText(deal.status)}
										</Badge>
									</div>
								</div>
							</div>
						{/each}
					</div>
				</CardContent>
			</Card>

			<!-- Upcoming Events -->
			<Card>
				<CardHeader>
					<CardTitle class="flex items-center justify-between">
						<span>Upcoming Events</span>
						<Button variant="outline" size="sm">
							<Plus class="h-4 w-4 mr-2" />
							Schedule
						</Button>
					</CardTitle>
					<CardDescription
						>Your scheduled meetings and events</CardDescription
					>
				</CardHeader>
				<CardContent>
					<div class="space-y-4">
						<div
							class="flex items-center space-x-3 p-3 rounded-lg bg-blue-50 border border-blue-200"
						>
							<Calendar class="h-5 w-5 text-blue-600" />
							<div class="flex-1">
								<p class="text-sm font-medium">
									Due Diligence - TechFlow Solutions
								</p>
								<p class="text-xs text-muted-foreground">
									Tomorrow, 10:00 AM
								</p>
							</div>
							<Badge variant="outline" class="text-xs"
								>Due Diligence</Badge
							>
						</div>

						<div
							class="flex items-center space-x-3 p-3 rounded-lg bg-green-50 border border-green-200"
						>
							<Calendar class="h-5 w-5 text-green-600" />
							<div class="flex-1">
								<p class="text-sm font-medium">
									Board Meeting - GreenEnergy Corp
								</p>
								<p class="text-xs text-muted-foreground">
									Friday, 2:00 PM
								</p>
							</div>
							<Badge variant="outline" class="text-xs"
								>Board Meeting</Badge
							>
						</div>

						<div
							class="flex items-center space-x-3 p-3 rounded-lg bg-purple-50 border border-purple-200"
						>
							<Calendar class="h-5 w-5 text-purple-600" />
							<div class="flex-1">
								<p class="text-sm font-medium">
									Startup Pitch Event
								</p>
								<p class="text-xs text-muted-foreground">
									Next Monday, 6:00 PM
								</p>
							</div>
							<Badge variant="outline" class="text-xs"
								>Pitch Event</Badge
							>
						</div>
					</div>
				</CardContent>
			</Card>
		</div>
	</div>
</div>

// migrate/frontend/pages/dashboard/investor/index.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Badge } from '@/components/ui/badge'
import { useInvestor } from '@/composables/useInvestor'

interface Startup {
  id: string
  name: string
  shortDescription: string
  stage: string
  industry: string
  region: string
  fundingNeeded: string
  teamSize: number
  foundedYear: number
  metrics: {
    mrr: number
    growth: number
    users: number
  }
  lastActive: string
  matchScore: number
}

interface InvestorStats {
  totalOpportunities: number
  savedStartups: number
  unreadMessages: number
  matches: number
  portfolioValue: number
  activeDeals: number
  totalInvested: number
  averageTicketSize: number
}

const { investor, isLoading, error } = useInvestor()

// State for startups
const startups = ref<Startup[]>([])
const savedStartups = ref<Startup[]>([])
const newOpportunities = ref<Startup[]>([])
const messages = ref<any[]>([])

// Filter states
const searchQuery = ref('')
const selectedIndustry = ref('all')
const selectedStage = ref('all')
const selectedRegion = ref('all')
const sortBy = ref('newest')

// Enhanced Stats
const stats = ref<InvestorStats>({
  totalOpportunities: 156,
  savedStartups: 24,
  unreadMessages: 8,
  matches: 12,
  portfolioValue: 2500000,
  activeDeals: 5,
  totalInvested: 1200000,
  averageTicketSize: 150000
})

// Mock data for demonstration
const mockStartup: Startup = {
  id: '1',
  name: 'TechCorp AI',
  shortDescription: 'AI-powered business intelligence platform',
  stage: 'Series A',
  industry: 'AI/ML',
  region: 'North America',
  fundingNeeded: '$5M',
  teamSize: 15,
  foundedYear: 2022,
  metrics: {
    mrr: 125000,
    growth: 25,
    users: 1500
  },
  lastActive: '2h ago',
  matchScore: 92
}

onMounted(async () => {
  // TODO: Implement data fetching
  // This would typically fetch from your API
  newOpportunities.value = Array(6).fill(mockStartup).map((s, i) => ({
    ...s,
    id: String(i + 1),
    matchScore: Math.floor(85 + Math.random() * 15)
  }))
})

const applyFilters = () => {
  // TODO: Implement filtering logic
}

const sortStartups = () => {
  // TODO: Implement sorting logic
}

// Format currency helper
const formatCurrency = (value: number): string => {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    notation: 'compact',
    maximumFractionDigits: 1
  }).format(value)
}
</script>

<template>
  <div class="container mx-auto py-8 space-y-8">
    <!-- Loading State -->
    <div v-if="isLoading" class="flex justify-center items-center h-64">
      <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900"></div>
    </div>

    <!-- Error State -->
    <div v-else-if="error" class="text-center text-red-500">
      {{ error }}
    </div>

    <!-- Main Dashboard -->
    <div v-else>
      <!-- Header Section -->
      <div class="flex justify-between items-center mb-8">
        <div>
          <h1 class="text-3xl font-bold">Investor Dashboard</h1>
          <p class="text-muted-foreground">Welcome back! Here's your investment overview</p>
        </div>
        <Button size="lg" class="gap-2">
          <i class="i-lucide-plus-circle" />
          New Search
        </Button>
      </div>

      <!-- Enhanced Stats Overview -->
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
        <!-- Investment Overview Card -->
        <Card class="col-span-2">
          <CardHeader>
            <CardTitle>Investment Overview</CardTitle>
          </CardHeader>
          <CardContent class="grid grid-cols-2 gap-4">
            <div class="space-y-1">
              <p class="text-sm text-muted-foreground">Portfolio Value</p>
              <p class="text-2xl font-bold">{{ formatCurrency(stats.portfolioValue) }}</p>
            </div>
            <div class="space-y-1">
              <p class="text-sm text-muted-foreground">Total Invested</p>
              <p class="text-2xl font-bold">{{ formatCurrency(stats.totalInvested) }}</p>
            </div>
            <div class="space-y-1">
              <p class="text-sm text-muted-foreground">Active Deals</p>
              <p class="text-2xl font-bold">{{ stats.activeDeals }}</p>
            </div>
            <div class="space-y-1">
              <p class="text-sm text-muted-foreground">Avg. Ticket Size</p>
              <p class="text-2xl font-bold">{{ formatCurrency(stats.averageTicketSize) }}</p>
            </div>
          </CardContent>
        </Card>

        <!-- Activity Stats -->
        <Card>
          <CardHeader>
            <CardTitle>Pipeline Activity</CardTitle>
          </CardHeader>
          <CardContent class="space-y-4">
            <div class="space-y-1">
              <div class="flex justify-between">
                <span class="text-sm text-muted-foreground">New Opportunities</span>
                <Badge variant="secondary">{{ stats.totalOpportunities }}</Badge>
              </div>
              <div class="flex justify-between">
                <span class="text-sm text-muted-foreground">Saved Startups</span>
                <Badge variant="secondary">{{ stats.savedStartups }}</Badge>
              </div>
            </div>
          </CardContent>
        </Card>

        <!-- Communication Stats -->
        <Card>
          <CardHeader>
            <CardTitle>Communications</CardTitle>
          </CardHeader>
          <CardContent class="space-y-4">
            <div class="space-y-1">
              <div class="flex justify-between">
                <span class="text-sm text-muted-foreground">Unread Messages</span>
                <Badge>{{ stats.unreadMessages }}</Badge>
              </div>
              <div class="flex justify-between">
                <span class="text-sm text-muted-foreground">Active Matches</span>
                <Badge variant="secondary">{{ stats.matches }}</Badge>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <!-- Main Content -->
      <Tabs default-value="opportunities" class="w-full">
        <TabsList >
          <TabsTrigger value="opportunities" class="flex gap-2">
            <i class="i-lucide-sparkles" />
            New Opportunities
          </TabsTrigger>
          <TabsTrigger value="saved" class="flex gap-2">
            <i class="i-lucide-bookmark" />
            Saved Startups
          </TabsTrigger>
          <TabsTrigger value="messages" class="flex gap-2">
            <i class="i-lucide-mail" />
            Messages
            <Badge v-if="stats.unreadMessages" variant="secondary" class="ml-1">
              {{ stats.unreadMessages }}
            </Badge>
          </TabsTrigger>
          <TabsTrigger value="matches" class="flex gap-2">
            <i class="i-lucide-heart" />
            Matches
          </TabsTrigger>
        </TabsList>

        <!-- Filter Bar -->
        <div class="flex flex-wrap gap-4 my-6">
          <Input
            v-model="searchQuery"
            placeholder="Search startups..."
            class="flex-1 min-w-[200px]"
          >
            <template #prefix>
              <i class="i-lucide-search text-muted-foreground" />
            </template>
          </Input>
          <Select v-model="selectedIndustry">
            <SelectTrigger class="w-[180px]">
              <SelectValue placeholder="Industry" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Industries</SelectItem>
              <SelectItem value="tech">Technology</SelectItem>
              <SelectItem value="healthcare">Healthcare</SelectItem>
              <SelectItem value="fintech">FinTech</SelectItem>
              <SelectItem value="ai">AI/ML</SelectItem>
              <SelectItem value="saas">SaaS</SelectItem>
            </SelectContent>
          </Select>
          <Select v-model="selectedStage">
            <SelectTrigger class="w-[180px]">
              <SelectValue placeholder="Stage" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Stages</SelectItem>
              <SelectItem value="seed">Seed</SelectItem>
              <SelectItem value="series-a">Series A</SelectItem>
              <SelectItem value="series-b">Series B</SelectItem>
              <SelectItem value="series-c">Series C</SelectItem>
            </SelectContent>
          </Select>
          <Select v-model="selectedRegion">
            <SelectTrigger class="w-[180px]">
              <SelectValue placeholder="Region" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Regions</SelectItem>
              <SelectItem value="north-america">North America</SelectItem>
              <SelectItem value="europe">Europe</SelectItem>
              <SelectItem value="asia">Asia</SelectItem>
              <SelectItem value="latam">Latin America</SelectItem>
            </SelectContent>
          </Select>
          <Select v-model="sortBy">
            <SelectTrigger class="w-[180px]">
              <SelectValue placeholder="Sort by" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="newest">Newest First</SelectItem>
              <SelectItem value="match">Match Score</SelectItem>
              <SelectItem value="funding">Funding Amount</SelectItem>
              <SelectItem value="growth">Growth Rate</SelectItem>
            </SelectContent>
          </Select>
        </div>

        <!-- Opportunities Tab -->
        <TabsContent value="opportunities">
          <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <Card v-for="startup in newOpportunities" :key="startup.id" class="hover:shadow-lg transition-shadow">
              <CardHeader>
                <div class="flex justify-between items-start">
                  <div class="space-y-1.5">
                    <CardTitle class="flex items-center gap-2">
                      {{ startup.name }}
                      <Badge variant="default" class="text-xs">
                        {{ startup.matchScore }}% Match
                      </Badge>
                    </CardTitle>
                    <CardDescription>{{ startup.shortDescription }}</CardDescription>
                  </div>
                  <Badge>{{ startup.stage }}</Badge>
                </div>
              </CardHeader>
              <CardContent>
                <div class="space-y-4">
                  <div class="flex flex-wrap gap-2">
                    <Badge variant="secondary">{{ startup.industry }}</Badge>
                    <Badge variant="secondary">{{ startup.region }}</Badge>
                    <Badge variant="outline">{{ startup.teamSize }} team members</Badge>
                  </div>
                  
                  <div class="grid grid-cols-3 gap-2 py-2">
                    <div class="space-y-1">
                      <p class="text-sm text-muted-foreground">MRR</p>
                      <p class="font-medium">{{ formatCurrency(startup.metrics.mrr) }}</p>
                    </div>
                    <div class="space-y-1">
                      <p class="text-sm text-muted-foreground">Growth</p>
                      <p class="font-medium">+{{ startup.metrics.growth }}%</p>
                    </div>
                    <div class="space-y-1">
                      <p class="text-sm text-muted-foreground">Users</p>
                      <p class="font-medium">{{ startup.metrics.users }}</p>
                    </div>
                  </div>

                  <div class="flex items-center justify-between pt-2">
                    <p class="text-sm text-muted-foreground">Seeking {{ startup.fundingNeeded }}</p>
                    <p class="text-sm text-muted-foreground">Active {{ startup.lastActive }}</p>
                  </div>

                  <div class="flex justify-between items-center gap-2">
                    <Button variant="outline" class="flex-1">View Profile</Button>
                    <Button class="flex-1">Connect</Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        <!-- Other tabs remain the same -->
        <TabsContent value="saved">
          <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <!-- Similar card structure as opportunities -->
          </div>
        </TabsContent>

        <TabsContent value="messages">
          <div class="space-y-4">
            <!-- Message list structure -->
          </div>
        </TabsContent>

        <TabsContent value="matches">
          <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <!-- Similar card structure as opportunities -->
          </div>
        </TabsContent>
      </Tabs>
    </div>
  </div>
</template>
